//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedTechniquesUP.Desktop.RestaurantService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookingIdField;
        
        private System.DateTime FromTimeField;
        
        private System.DateTime ToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdvancedTechniquesUP.Desktop.RestaurantService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdvancedTechniquesUP.Desktop.RestaurantService.Table TableField;
        
        private int CustomerIdField;
        
        private int TableNumberField;
        
        private AdvancedTechniquesUP.Desktop.RestaurantService.SalesChannel salesChannelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FromTime {
            get {
                return this.FromTimeField;
            }
            set {
                if ((this.FromTimeField.Equals(value) != true)) {
                    this.FromTimeField = value;
                    this.RaisePropertyChanged("FromTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ToTime {
            get {
                return this.ToTimeField;
            }
            set {
                if ((this.ToTimeField.Equals(value) != true)) {
                    this.ToTimeField = value;
                    this.RaisePropertyChanged("ToTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.Table Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TableNumber {
            get {
                return this.TableNumberField;
            }
            set {
                if ((this.TableNumberField.Equals(value) != true)) {
                    this.TableNumberField = value;
                    this.RaisePropertyChanged("TableNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.SalesChannel salesChannel {
            get {
                return this.salesChannelField;
            }
            set {
                if ((this.salesChannelField.Equals(value) != true)) {
                    this.salesChannelField = value;
                    this.RaisePropertyChanged("salesChannel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private long DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((this.DocumentField.Equals(value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdvancedTechniquesUP.Desktop.RestaurantService.Booking[] BookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TableId {
            get {
                return this.TableIdField;
            }
            set {
                if ((this.TableIdField.Equals(value) != true)) {
                    this.TableIdField = value;
                    this.RaisePropertyChanged("TableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.Booking[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesChannel", Namespace="http://tempuri.org/")]
    public enum SalesChannel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Web = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desktop = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantService.RestaurantServiceSoap")]
    public interface RestaurantServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetBookingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookings", ReplyAction="*")]
        AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse GetBookings(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse> GetBookingsAsync(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookings", Namespace="http://tempuri.org/", Order=0)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequestBody Body;
        
        public GetBookingsRequest() {
        }
        
        public GetBookingsRequest(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBookingsRequestBody {
        
        public GetBookingsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponseBody Body;
        
        public GetBookingsResponse() {
        }
        
        public GetBookingsResponse(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdvancedTechniquesUP.Desktop.RestaurantService.Booking[] GetBookingsResult;
        
        public GetBookingsResponseBody() {
        }
        
        public GetBookingsResponseBody(AdvancedTechniquesUP.Desktop.RestaurantService.Booking[] GetBookingsResult) {
            this.GetBookingsResult = GetBookingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RestaurantServiceSoapChannel : AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServiceSoapClient : System.ServiceModel.ClientBase<AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap>, AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap {
        
        public RestaurantServiceSoapClient() {
        }
        
        public RestaurantServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap.GetBookings(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest request) {
            return base.Channel.GetBookings(request);
        }
        
        public AdvancedTechniquesUP.Desktop.RestaurantService.Booking[] GetBookings() {
            AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest inValue = new AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest();
            inValue.Body = new AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequestBody();
            AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse retVal = ((AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap)(this)).GetBookings(inValue);
            return retVal.Body.GetBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse> AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap.GetBookingsAsync(AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest request) {
            return base.Channel.GetBookingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsResponse> GetBookingsAsync() {
            AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest inValue = new AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequest();
            inValue.Body = new AdvancedTechniquesUP.Desktop.RestaurantService.GetBookingsRequestBody();
            return ((AdvancedTechniquesUP.Desktop.RestaurantService.RestaurantServiceSoap)(this)).GetBookingsAsync(inValue);
        }
    }
}
